# Generated by Django 3.0.5 on 2020-05-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/%Y.%m'),
        ),
    ]
